# 配置参考 ： https://segmentfault.com/a/1190000004315890
# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
#debug : true


################################################################################################################
###endpoint 基本配置：
################################################################################################################
info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
    title : 科技馆平台
    company: 正方软件股份有限公司
    ipc-license: 浙ICP备11024936
    addr: 浙江省杭州市西湖区紫霞街176号互联网创新创业园2号301
    copyright: 版权所有&copy Copyright 1999-2017 中国
    email: zfsoft@zfsoft.com
    fax: 0571-89902829
    tel: 0571-89902836


################################################################################################################
###内置应用容器（Tomcat）配置：
################################################################################################################
server:
  port: 8080
  # tomcat设置
  tomcat:
    accesslog:
      # 开启日志访问
      enabled: true
    max-http-header-size: 8192
    max-connections: 2000
    max-threads: 2000
  ssl:
    enabled: false
    key-alias: tomcat
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12

management:
  server:
    port: 54002
  health:
    mail:
      enabled: false
    redis:
      enabled: false
    rabbit:
      enabled: false
    cassandra:
      enabled: false
    couchbase:
      enabled: false
    elasticsearch:
      enabled: false
    mongo:
      enabled: false
    solr:
      enabled: false

################################################################################################################
###Spring Boot 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：
################################################################################################################
spring:
  messages:
    #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: i18n/messages
    #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    #cache-seconds: 6000
    #设定Message bundles的编码，默认: UTF-8
    encoding: UTF-8

    http:
      multipart:
        enabled: true
        max-file-size: 50MB
        max-request-size: 100MB

  profiles:
    active: dev

  #MVC
  mvc:
    static-path-pattern: /**
    view:
      prefix: classpath:/templates/
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - classpath:/templates/

  # 会话配置（交个Shiro管理，此处不再指定）：
  session:
    store-type: none

  # 缓存配置：
  cache:
    type: ehcache
    ehcache:
      config: classpath:/conf/ehcache/ehcache.xml

  # 数据源配置：
  datasource:
    name: ZFTAL_BOOT_STRUTS
    driver-class-name: oracle.jdbc.OracleDriver
    #oracle.jdbc.driver.OracleDriver
    #type: com.zfsoft.db.core.datasource.NewDruidDataSource
    #url: Kbs2u6NELkMD+i6RnR+aSRYguMAm9Sijs60p2ZfE8+wHkVsh0SdX85+Y60A4RnMl
    #username: 8J02YYS4gwOdDrhW0kL0ZQ==
    #password: 8J02YYS4gwOdDrhW0kL0ZQ==
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@10.71.19.133:1521:orcl
    #url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.1.71)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.1.72)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.1.73)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.1.74)(PORT = 1521))(LOAD_BALANCE = yes)(FAILOVER = ON)(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = jhc)(FAILOVER_MODE =(TYPE = SELECT)(METHOD = BASIC)(RETIRES = 20)(DELAY = 15))))
    username: ZFTAL_BOOT_STRUTS
    password: ZFTAL_BOOT_STRUTS
    # Druid的数据源配置：
    druid:
      enabled: true
      #配置这个属性的意义在于，如果存在多个数据源，监控的时候可以通过名字来区分开来。如果没有配置，将会生成一个名字，格式是：”DataSource-” + System.identityHashCode(this)
      #name: DataSource-Test
      #这一项可配可不配，如果不配置druid会根据url自动识别dbType，然后选择相应的driverClassName
      #driver-class-name: oracle.jdbc.driver.OracleDriver
      #url:
      #username: xxx
      #password: xxx
      #initialSize: 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时；默认 15
      initial-size: 15
      #连接池最大连接数量
      max-active: 50
      #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
      max-wait: 60000
      #连接池最小连接数量；默认 5
      min-idle: 5
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒;有两个含义：1) Destroy线程会检测连接的间隔时间 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位：毫秒
      min-evictable-idle-time-millis: 300000
      #超过时间限制是否回收
      remove-abandoned: true
      #超过时间限制多长，单位：毫秒 ，180000毫秒=3分钟
      remove-abandoned-timeout-millis: 180000
      #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query: SELECT 1 FROM DUAL
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。建议配置为true，不影响性能，并且保证安全性。
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。5.5及以上版本有PSCache，建议开启。
      pool-prepared-statements: true
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 100
      #Druid的监控统计功能:属性类型是字符串，通过别名的方式配置扩展插件
      #filters: mergeStat,wall,slf4j
      # 自定义过滤器参数
      proxy-filter: true
      wall-filter:
        # 对被认为是攻击的SQL进行LOG.error输出
        log-violation: true
        # 对被认为是攻击的SQL抛出SQLExcepton
        throw-exception: true
        config:
          # 是否允许语句中存在注释，Oracle的用户不用担心，Wall能够识别hints和注释的区别
          comment-allow: true
          # 是否允许非以上基本语句的其他语句，缺省关闭，通过这个选项就能够屏蔽DDL
          none-base-statement-allow: true
          # 是否允许一次执行多条语句，缺省关闭
          multi-statement-allow: true
          # 解除union关键字检查
          select-union-check: false
          # 是否允许执行锁定表操作
          lock-table-allow: true

      #Druid监控
      stat-view-servlet:
        enabled: true
        pointcut-patterns:
          - com.zfsoft.boot.demo.web.controller
      dynamic:
        enabled: true
  ################################################################################################################
  ###Flyway (FlywayMigrationProperties) 数据库迁移脚本版本管理（实现软件版本升级数据库自动升级）配置：
  ################################################################################################################
#  flyway:
#    enabled: true
#    #是否忽略版本迁移
#    ignore-migration: false
#    #指定SQL起始版本信息
#    baseline-on-migrate: true
#    baseline-version: 1.0.0.0
#    baseline-description: 业务框架、权限管理、日志管理初始化
#    #如果已经有版本1和3，当发现新的版本2时，如果此参数为true,将会把版本2作为当前版本
#    out-of-order: false
#    #在进行版本升级前是否进行SQL版本信息校验
#    validate-on-migrate: true
#    #安全模式下不能进行表结构清理
#    safe-mode: true
#    #设置如果验证失败是否删除表结构
#    clean-on-validation-error: true
#    #禁止对数据库进行相关清除操作
#    clean-disabled: true

################################################################################################################
###mybatis (MybatisProperties) 基本配置：
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
mybatis:
  check-config-location: true
  config-location: classpath:config/mybatis-config.xml
  type-aliases-package: com.zfsoft.boot.init.dao.entities, com.zfsoft.boot.authz.dao.entities, com.zfsoft.boot.zhjx.dao.entities, com.zfsoft.**.model
  #自动扫描Dao的根目录，多个使用,分割
  base-package: com.zfsoft.**.dao
  #Mapper.xml匹配规则
  mapper-locations: classpath:mapper/*/*.xml



      ################################################################################################################
      ###基于 starter 的自动配置
    #基于 @MapperScan 注解的手工配置
################################################################################################################
#pagehelper
#pagehelper:
#  helperDialect: oracle
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#  returnPageInfo: check
#
#mapper:
#  mappers:
#    - tk.mybatis.mapper.common.Mapper
#    - tk.mybatis.mapper.common.Mapper2
#  notEmpty: true
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.Mapper2
  notEmpty: true
################################################################################################################
###ZFtal安全组件（跨域、XSS等）配置：
################################################################################################################
zftal:
  http:
    safety:
      enabled: true
      url-patterns: /*
      definition-map:
        '[/]' : httpHeaderControl,httpMethodControl
        '[/webjars/**]' : noneControl
        '[/assets/**]' : noneControl
        '[/druid/**]' : noneControl
        '[/**]' : httpHeaderControl,httpMethodControl
      http-cors-filter:
        enabled: true
        access-control-allow-origin: '*'
        access-control-allow-credentials: true
        access-control-allow-headers: X-Requested-With
        access-control-allow-methods: GET,POST
      http-header-filter:
        enabled: true
        x-content-type-options: SAMEORIGIN
        x-frame-options: nosniff
        x-xss-protection: 1; mode=block
      http-methods-filter:
        enabled: true
        allowed-http-methods:
          - GET
          - POST
      http-richtext-xss-filter:
        enabled: true
        default-policy: classpath:conf/security/zfsoft-antixss-policy.xml
      http-xss-filter:
        enabled: false


################################################################################################################
###Shiro 权限控制基本配置：
################################################################################################################
shiro:
  enabled: true
  validate-captcha: false
  login-url: /authz/login/slogin
  redirect-url: /authz/login/index
  success-url: /index
  unauthorized-url: /error
  annotations:
    enabled: true
  web:
    enabled: true
  filter-chain-definition-map:
    '[/]' : anon
    '[/*favicon.ico]' : anon
    '[/webjars/**]' : anon
    '[/assets/**]' : anon
    '[/html/**]' : anon
    '[/error*]' : anon
    '[/logo/**]' : anon
    '[/kaptcha*]' : anon
    '[/pwdmgr/retake/**]' : anon
    '[/pwdmgr/update/**]' : anon
    '[/authz/login_code*]' : anon
    '[/authz/login/getPublicKey*]' : anon
    '[/authz/login/index*]' : anon
    '[/authz/login/slogin*]' : authc
    '[/qrCode/**]' : anon
    '[/wx/**]' : anon
    '[/wxpage/**]' : anon
    '[/druid/*]' : roles[admin]
    '[/api/**]' : anon

    '[/kejiguan/**]': anon
    '[/swagger-ui.html]': anon
    '[/swagger-resources/**]': anon
    '[/webjars/*]': anon

    '[/ws/**]' : anon
    '[/sockets/**]' : anon
    '[/topic/**]' : anon
    '[/monitoring/**]' : anon
    '[/mUser/**]' : anon
    '[/mDevice/**]' : anon
    '[/mta/**]' : anon
    '[/logout]' : logout
    '[/index]' : sessionExpired,sessionControl,authc
    '[/**]' : sessionExpired,sessionControl,authc




################################################################################################################
###Rocketmq 客户端基本配置：
################################################################################################################
rocketmq:
  producer:
    enabled: true
    producer-group: druid-shiro-rocketmq-group
    instance-name: druid-shiro-rocketmq-instance
    namesrv-addr: 10.71.19.153:9876

  # ConsumeType.CONSUME_PASSIVELY : "PUSH" 模式
  consume-passively:
    enabled: true
    consumer-group: druid-shiro-rocketmq-group
    instance-name: druid-shiro-rocketmq-instance
    namesrv-addr: 10.71.19.153:9876
      # subscription:
      #topic名称  : 根据实际情况设置消息的tag
      #数据中心数据上行主题  : 各个系统的标记
    #Topic-DSB : TagA-Input || TagB-Input || TagC-Input || TagD-Input || Notice-Input
#   event:
#     definition-map:
#       /Topic-DC-Input/TagA-Input/** : inDbHandler
#       /Topic-DC-Input/TagB-Input/** : smsHandler
#       /Topic-DC-Input/Notice-Input/** : noticeHandler

################################################################################################################
###logging (log4j2) 基本配置：
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
#logging:
#  log4j:
#    enabled: true
#    table-name: ZFTAL_LOG_BIZ
#  config: classpath*:log4j3.xml

